echo "DB_HOST = 'your_host'" > .streamlit/secrets.toml
echo "DB_PORT = '5432'" >> .streamlit/secrets.toml
echo "DB_USER = 'postgres'" >> .streamlit/secrets.toml
echo "DB_PASSWORD = 'your_password'" >> .streamlit/secrets.toml
echo "DB_NAME = 'weatherstack_etl'" >> .streamlit/secrets.toml
